version: '3.8'
services:
  mysql-docker-container:
    image: mysql:8.0.30-oracle
    container_name: mysql-docker-container
    ports:
      - 3306:3306
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: n01s4ud3mv4ng
      MYSQL_DATABASE: koro_shop
  springboot-docker-container:
    image: hungpro989/koroapp:v1.0.0
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - backend
networks:
  backend:
    name: spring-app-network
volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond:
